INSERT INTO `social_network`.post (`authorized_view`, `date_created`, `text_content`, `date_updated`, `user_user_id`)
VALUES
    ('public', '2023-07-25', 'Hôm nay là một ngày đẹp trời và tôi cảm thấy rất vui vì đã hoàn thành dự án của mình.', null, 1),
#     ('public', '2023-07-25', 'Tôi vừa trở về từ chuyến đi du lịch tuyệt vời ở Nha Trang. Cảm giác thư giãn và hạnh phúc đến không tả được.', null, 1),
#     ('public', '2023-07-25', 'Đã lâu không gặp các bạn của mình. Hy vọng sẽ có thời gian để gặp gỡ và trò chuyện.', null, 1),
    ('private', '2023-07-25', 'Tôi vừa đọc một cuốn sách rất hay về lãnh đạo và muốn chia sẻ với mọi người những bài học quý báu từ cuốn sách đó.', null, 1),
    ('public', '2023-07-25', 'Một ngày rất bận rộn với công việc nhưng tôi vẫn cảm thấy rất hạnh phúc vì đã hoàn thành tất cả những gì cần làm.', null, 2),
#     ('public', '2023-07-25', 'Tôi vừa xem một bộ phim rất hay và muốn giới thiệu với mọi người. Đó là câu chuyện về tình yêu và hy vọng.', null, 2),
#     ('public', '2023-07-25', 'Cuối tuần này, tôi sẽ tham gia một cuộc thi thể thao và hy vọng sẽ có thể giành chiến thắng. Hãy cùng tôi cổ vũ nhé!', null, 2),
    ('private', '2023-07-25', 'Tôi vừa tìm thấy một công việc mới và rất phấn khích về điều đó. Hy vọng sẽ có một tương lai tươi sáng.', null, 2),
#     ('public', '2023-07-25', 'Hôm nay tôi đã học được một bài học quan trọng về sự kiên trì và tinh thần không bỏ cuộc. Hy vọng sẽ giúp ích cho mọi người.', null, 3),
#     ('public', '2023-07-25', 'Gia đình là nơi cuộc sống bắt đầu và tình yêu không bao giờ kết thúc..', null, 3),
    ('private', '2023-07-25', 'Cuối cùng vẫn chỉ có tình cảm gia đình là thứ tình yêu vô điều kiện duy nhất trong cuộc đời mỗi con người', null, 3),
#     ('public', '2023-07-25', 'Gia đình là nơi tốt nhất mà bạn tìm về với bình yên, thương mà không cần điều kiện, là nơi có cuộc sống tốt nhất để tao nên vỏ bọc bảo vệ.', null, 3),
#     ('public', '2023-07-25', 'Gia đình người ta có nhiều nơi để đến nhưng chỉ có một chốn để quay về..', null, 4),
    ('private', '2023-07-25', 'Một cuộc hôn nhân tuyệt vời không phải là mọi thứ giữa đôi bênông cần lo lắng mối quan hệ của hai người sẽ đổ vỡ', null, 4),
    ('public', '2023-07-25', 'Người nói yêu bạn chưa chắc đã đợi được bạn, nhưng người đợi được bạn chắc chắn rất yêu bạn', null, 4),
    ('public', '2023-07-25', 'Cuộc đời tôi đang ở cái giai đoạn mà tôi sẽ né mọi loại tranh luận cho nhẹ đầu. Kể cả khi bạn bảo 1 + 1 = 5. Bạn nói chuẩn, xuất sắc!.', null, 4),
#     ('public', '2023-07-25', 'Thời gian là vị bác sĩ giỏi nhưng lại là người trang điểm tồi.', null, 5),
    ('public', '2023-07-25', 'Cuộc đời ngắn lắm, hãy cười khi bạn vẫn còn răng..', null, 5),
    ('public', '2023-07-25', 'Hạnh phúc không phải là nhận được mà là cho đi.', null, 5),
#     ('public', '2023-07-25', 'Bạn không thể tìm thấy hạnh phúc nếu bạn không tìm thấy lòng nhân ái trong trái tim mình.', null, 5),
    ('public', '2023-07-25', 'Thời điểm đáng sợ nhất luôn luôn là ngay trước khi bạn bắt đầu. Sau đó, mọi thứ nhất định sẽ tốt đẹp hơn.', null, 6),
#     ('public', '2023-07-25', 'Một ngày nào đó, những góc cạnh trong bạn sẽ bị thế giới bào mòn, bạn sẽ i, bạn sẽ học được cách mỉm cười với người bạn ghé.', null, 6),
    ('public', '2023-07-25', ' Em biết anh sẽ đến, nên em chờ.', null, 6),
#     ('public', '2023-07-25', ' Thời bình hóa ra cũng không tốt như em tưởng tượng, vì em không thể thay anh đỡ đạn, để anh mãi mãi không thể quên em..', null, 6),
#     ('public', '2023-07-25', 'Nếu có một ngày, em không , dù trong lòng anh không muốn tới cỡ nào, cũng xin anh nhất định phải nói, người anh yêu nhất là em.', null, 7),
    ('public', '2023-07-25', 'Trên đời này, có rất nhiều điều là vĩnh cửu, nhưng tuyệt nhiên, tình yêu không phải là 1 trong số đó.', null, 7),
#     ('public', '2023-07-25', 'Có ân mình đầu hàng.hịu được cô đơn, mới ôm được náo nhiệt, vào những tháng năm còn có thể cố gắng, đừng chọn cách sống an nhàn.', null,7),
    ('public', '2023-07-25', 'Trăng dưới nước là trăng trên trời, người trước mặt là người trong tim.', null, 7),
#     ('public', '2023-07-25', 'Nếu bạn vô cùng muốn một ai đó, vậy hãy để người ấy ra đi, đợi đến khi người ấy trở về tìm bạn, bạn sẽ có được người ấy mãi mãi.', null, 8),
    ('public', '2023-07-25', ' Tất cả mọi việc, đến cuối cùng rồi sẽ tốt đẹp hơn, nếu nó không tốt hơn, vậy chứng minh còn chưa tới cuối cùng', null, 8),
    ('public', '2023-07-25', 'Sợ nhất là cả đời tầm thường, không tiến thủ, còn an ủi bản thân đó là bình thản, đáng ngưỡng mộ', null, 8),
    ('public', '2023-07-25', 'Người đời ai cũng muốn cứu thế giới, lại không ai nghĩ đến một việc đơn giản như giúp mẹ rửa bát.', null, 8),
    ('public', '2023-07-25', 'Người đời ai cũng muốn cứu thế giới, lại không ai nghĩ đến một việc đơn giản như giúp mẹ rửa bát.', null, 9),
#     ('public', '2023-07-25', 'Người đời ai cũng muốn cứu thế giới, lại không ai nghĩ đến một việc đơn giản như giúp mẹ rửa bát.', null, 9),
#     ('public', '2023-07-25', ' Phải có một cuộc sống giản dị nhất, cùng ước vọng xa xôi nhất, dù ngày mai trời đông giá rét, dù đường dài ngựa chẳng cất nổi chân.', null, 9),
    ('public', '2023-07-25', 'Bạn nên biết rằng không có việc gì là không thể.', null, 9),
#     ('public', '2023-07-25', 'Trong lòng mỗi người đều có nhiều cánh cửa, những đau buồn suy nghĩ, đôi khi không cần thiết phải mở toang cho mọi người cùng thấ', null, 10),
    ('public', '2023-07-25', 'Thỉnh thoảng bạn cần đi xa, không phải để cho ai đó nh chính bạn hiểu và nhận ra giá trị của chính bản thân mình.', null, 10),
#     ('public', '2023-07-25', 'Nỗi tuyệt vọng lớn nhất trên đời, không phải là từ đầu không có hy vọng, mà là mang lại hy vọng sau đó lại không chút lưu tình cướp đi', null, 10),
    ('public', '2023-07-25', 'Nếu như nước mắt mà còn giả dối được thì trên đời này còn thứ gì để có thể coi là thật được đây', null, 10),
#     ('public', '2023-07-25', 'Thật ra quên không phải là cái đau khổ nhất, người đau khổ là người có trí nhớ.', null, 11),
#     ('public', '2023-07-25', 'Hóa ra khoảng cách giữa con người cũng tùy lúc mà gần, hay xa.', null, 11),
    ('public', '2023-07-25', 'Người cô đơn quá lâu sẽ không có thói quen yêu và được yêu', null, 11),
    ('public', '2023-07-25', ' Người cô đơn quá lâu sẽ không có thói quen yêu và được yêu', null, 11),
#     ('public', '2023-07-25', 'Hạnh phúc của mình phải do chính mình nắm bắt, phải do chính mình bảo vệ.', null, 12),
    ('public', '2023-07-25', 'Thế giới này, biết được càng nhiều thì bạn càng không vui vẻ. Sự thật luôn tàn nhẫn hơn bạn tưởng tượng', null, 12),
    ('public', '2023-07-25', 'Những thứ đẹp nhất luôn là những thứ lâu lâu mới được gặp.', null, 12),
#     ('public', '2023-07-25', 'Cuộc sống không tặng cho ta thứ gì cả. Những gì cuộc sống đem lại cho ta đều được ghi giá một cách kín đáo..', null, 12),
    ('public', '2023-07-25', ' Tất cả mọi thứ chỉ quý giá tại 2 thời điểm: Trước khi có được và sau khi mất đi.', null, 13),
#     ('public', '2023-07-25', ' 2 điều mang lại hạnh phúc và thành công trong cuộc sống: Cách bạn xoay xở khi không có gì và thái độ của bạn khi bạn có mọi thứ', null, 13),
    ('public', '2023-07-25', 'Thái độ tốt nhất chính là: “Lưng của tôi không phải là một hộp thư thoại. Vui lòng nói bất cứ điều gì bạn muốn trước mặt tô', null, 13),
#     ('public', '2023-07-25', 'Thái độ tốt nhất chính là: “Lưng của tôi không phải là một hộp thư thoại. Vui lòng nói bất cứ điều gì bạn muốn trước mặt tô', null, 13),
    ('public', '2023-07-25', 'Đừng che dấu tình yêu và sự dịu dàng của mình cho đến khi bHãy nói những lời thân thương khi bạn còn nghe được và tim bạn còn rung động.', null, 14),
#     ('public', '2023-07-25', 'Sự chân thành là điều tốt đẹp nhất bạn có thể đem trao tặng một người. Sự thật,nh bạn và tình yêu đều tùy thuộc vào điều đó cả.', null, 14),
    ('public', '2023-07-25', 'Đừng nói mà hãy làm. Đừng huyên thuyên mà hãy hành động. Đừng hứa mà hãy chứng minh.', null, 14),
#     ('public', '2023-07-25', ' Im lặng và mỉm cười là 2 vũ khí lợi hại. Mỉm cười là cách để giải quyết nhiều vấn đề , im lặng là cách để tránh những vấn đề rắc rối xảy ra..', null, 14),
#     ('public', '2023-07-25', 'Lo lắng chỉ làm lãng phí thời gian, nó không làm thay đổi gì cả,  làm cho bạn lúc nào cũng bận rộn mà chẳng hoàn tất được gì cả.', null, 15),
    ('public', '2023-07-25', '“Cuộc sống chỉ mang lại cho chúng ta 10% cơ hội, 90% còn lại là do rải nghiệm thế nào với nó.”', null, 15),
#     ('public', '2023-07-25', 'Tiền bạc khó mua được sức khỏe nhưng sức khỏe sẽ được tăng cường hơn  bạc khó mược hạnh phúc nhưng muốn có hạnh phúc, buộc phải có sức khỏe.', null, 15),
    ('public', '2023-07-25', 'Bạn xứng đáng được ngủ một giấc thật ngon, không cần vì một người đang ngủ say chẳng hề hay biết kia mà mất ngủ thêm nữa.', null, 15),
    ('public', '2023-07-25', 'Bạn không cần phải yêu một người một cách cẩn thận, dè dặt như thế, cũng không cần bạn phải hoàn hảo, một vết xước', null, 16),
#     ('public', '2023-07-25', 'Họ tốt đến đâu không quan trọng, bởi những thứ đó thuộc về họ. Họ tốt với bạn thế nào mới quan trọng, bởi những thứ đó thuộc về bạn.', null, 16),
#     ('public', '2023-07-25', 'Ai không giả dối, ai không dễ thay đổi, không ai là ai của ai hết. Hà tất phải coi một số người, một số chuyện quan trọng đến thế', null, 16),
    ('public', '2023-07-25', 'Thế giới bạn không bước vào được thì đừng cố chen vào, làm khó người khác, lỡ dở mình, hà tất chứ?', null, 16),
#     ('public', '2023-07-25', 'Lúc nào tôi cũng bay theo hướng bay của người khác. Lần này tôi sẽ bay theo con đường mà tôi đã lựa chọn.', null, 17),
    ('public', '2023-07-25', 'Người đàn ông tình nguyện vì bạn mà bạn, bởi vì những thứ mà anh ta vứt bỏ đều là những thứ thiết thực nhất gắn liền với cuộc đời anh ta', null, 17),
#     ('public', '2023-07-25', 'Người đàn ông tình nguyện vì bạn mà theo đuổi mọi thứ chưa hẳn đã thật lòng yêu bạn, bởi vì thứ mà anh ta theo đuổi được không hẳn thuộc về bạn', null, 17),
    ('public', '2023-07-25', 'Phụ nữ, không cần phải nghiêng nước nghiêng thành, chỉ cần một người đàn ông nghiêng về cô ấy cả một đời!.', null, 17),
    ('public', '2023-07-25', 'Phụ nữ không có sức hấp dẫn mới cảm thấy đàn ông trăng hoa. Đàn ông không có thực lực mới cảm thấy phụ nữ thực dụng!', null, 18),
#     ('public', '2023-07-25', 'Người quan tâm đến tôi, tôi sẽ quan tâm lại gấp bội! Người không quan tâm đến tôi, bạn dựa vào cái gì mà bảo tôi phải tiếp tụ', null, 18),
#     ('public', '2023-07-25', ' Ở nơi nào đó trên thế giới này nếu có anh ấy xuất hiện, thì những người khác đều trở thành tạm bợ.', null, 18),
    ('public', '2023-07-25', 'Giá như tớ có thể đọc được những dòng suy nghĩ từ cậhĩ gì về tớ. Tớ ko thể chờ đợi hoài được vì càng đợi tớ lại càng cảm thấy tuyệt vọng.', null, 18),
#     ('public', '2023-07-25', 'Có những chuyện bạn biết rất rõ nhưng lại không thể nói ra. Bởi một khi đã phơi bày, chẳng ai là người vui vẻ cả…', null, 19),
#     ('public', '2023-07-25', 'Tên của anh khi viết xuống giấanh xuân của em. Thực ra anh không biết rằng anh chính là ước mơ của em. ” Hàn Thiên.', null, 19),
    ('public', '2023-07-25', 'Gặp gỡ, là một kiếp nạn hạnh phúc, cũng là một nét đẹp sai lầm.Quên nhau, là một sự khởi đầu hoang mang, cũng là sự kết thúc trong trẻo', null, 19),
    ('public', '2023-07-25', 'Gặp nhau, quen nhau giữa biển người mênh mông chính là duyên, lưu lạc giữa hồng trần lại không lãng quên chính là duyên.', null, 19),
    ('public', '2023-07-25', ' Có một người, tuy đã nhiều năm trôi qua nhưng vẫn được bạn đặt ở nơi sâu nhất trong lòng, sâu đến nỗi chính bạn cũng đã quên', null, 20),
    ('public', '2023-07-25', 'Muốn phát tiết thật dễ dàng, muốn nhẫn nại lại rất khó khăn', null, 20),
#     ('public', '2023-07-25', 'Bạn bè không quan trọng đứa nào giúp đứa nào nhiều hơn. Quan trọng là lúc khó còn có đứa nào không?', null, 20),
    ('public', '2023-07-25', 'Bạn không thể điều khiển hướng gió, chỉ có thể đn không cần phải thấy hết các bậc thang mà chỉ cần đi bước đầu tiên với một niềm tin', null, 20),
    ('public', '2023-07-25', 'Cuộc sống, ngay cả khi có một ngàn lý do để làm cho bạn khóc, bạn vẫn hải tìm một triệu lý do để giữ nụ cười.', null, 21),
#     ('public', '2023-07-25', 'Làm người phải tự tin, nhưng không đượười nên khiêm tốn, nhưng không được khiêm tốn đến mức đánh mất lòng tự tin của mình.', null, 21),
#     ('public', '2023-07-25', 'Cuộc sống quan trọng nhất là sự lựa chọn', null, 21),
    ('public', '2023-07-25', 'Thiên Chúa ban cho tất cả mọi người 24 giờ, còn 24 giờ ấy có giá trị bao nhiêu là do mỗi người tự định lấy.', null, 21),
    ('public', '2023-07-25', ' Ở thực trạng xã hội hiện nay, sự thờ ơ của người tốt còn đáng sợ hơn những thứ xấu xí của xã hội.', null, 22),
    ('public', '2023-07-25', 'Muốn đổi thói quen, phải thay hành động.', null, 22),
    ('public', '2023-07-25', 'Tôi tự nhủ với bản thân mình rằng, những lúc buồn có thể khóc những giờ phút đó, cần phải ngẩng đầu cười thật xinh tươi.', null, 22),
#     ('public', '2023-07-25', 'Tôi tự nhủ với bản thân mình rằng, cần  cần nghĩ có phải có ai đang để tâm tới mình hay không. Bởi một người cũng có thể sống cuộc sống tươi đẹp.', null, 23),
#     ('public', '2023-07-25', 'Tôi tự nhủ với bản thân mình kể người khác nhìn mình bằng con mắt nào đi chăng nữa, dù cảnh, tôi vẫn có bản thân tin tưởng mình.', null, 23),
    ('public', '2023-07-25', 'Cuộc sống không phải là phim ảnh, không có nhiều đến thế... những lần không hẹn mà gặp..', null, 23),
    ('public', '2023-07-25', ' Hãy giữ khuôn mặt bạn luôn hướng về ánh mặt trời, và bóng tối sẽ ngả phía sau bạn.', null, 23),
#     ('public', '2023-07-25', 'Ta không thể bắt đầu lại nhưng ta có thể mở đầu bây giờ và làm nên một kết thúc mới.', null, 24),
    ('public', '2023-07-25', 'Chẳng có gì trở nên dễ dàng hơn. Chỉ là bạn trở nên mạnh mẽ hơn mà thôi..', null, 24),
#     ('public', '2023-07-25', 'Cuộc sống có quyền đẩy bạn ngã nhưng ngồi đó than khóc hay đứng dậy và tiếp tục là quyền của bạn', null, 24),
    ('public', '2023-07-25', 'Lòng tin cũng giống như một tờ giấy, khi đã nhàu nát sẽ không bao giờ phẳng phiu được..', null, 25),
    ('public', '2023-07-25', 'Hãy cảm ơn những lúc bạn gặp khó khăn, bởi nếu không có khó khăn, bạn sẽ không có cơ hội để hiểu mình và trải nghiệm cuộc sống', null, 25),
    ('public', '2023-07-25', 'Bạn sẽ tìm thấy niềm vui khi giúp đỡ người khác bằng tất cả tấm lòng', null, 26),
    ('public', '2023-07-25', 'Nếu để ý đến những điều bạn đan sẽ nhận được nhiều hơn thế. Còn nếu chỉ để ý đến những điều bạn không có, bạn sẽ thấy mình không bao giờ có đủ', null, 26),
    ('public', '2023-07-25', 'Bạn cần sự hiểu biết và sáng tạo nênho bạn đôi bàn tay và trí óc để khám phá và làm việc.', null, 26),
#     ('public', '2023-07-25', ' chắc chắn sẽ có ai đó yêu bạn chỉ vì nụ cười của bạn thôi. Với thế giới bạn chỉ là một cá nhân nhưng đối với một ai đó, bạn là cả thế giới.', null, 27),
    ('public', '2023-07-25', ' Cuộc sống của bạn chỉ thật sự ý nghĩa và trọn vẹn khi bạn biết giữ gìn và nuôi dưỡng ước mơ, biết ghi nhận, biết tin vào những lời hứa.', null,27),
    ('public', '2023-07-25', 'Đta sẽ không hiểu được cuộc sống, không có được bản lĩnh, nghị lực như chhật công bằng, không phải vô cớ mà mọi điều xảy đến với ta', null, 28),
    ('public', '2023-07-25', 'Đừng bao giờ thay đổi mình vì người khác. Nếu họ không , thì cũng không xứng để có được một con người với nhiều điểm tốt là bạn.', null, 29),
    ('public', '2023-07-25', ' Đôi khi, không cẩn thận biết một số chuyện, mới phát hiện ra rằng những điều bản thân để tâm lại nực cười đến thế..', null, 29),
    ('public', '2023-07-25', 'Thế giới bạn không bước vào được thì đừng cố chen vào, làm khó người khác, lỡ dở mình, hà tất chứ?.', null, 30),
    ('public', '2023-07-25', 'Nếu bạn không thử, bạn sẽ không bao giờ biết được bạn có thể làm được những gì.', null, 31),
    ('public', '2023-07-25', 'Đừng lo lắng khi mọi người giỏ phá kỷ lục của mình mỗi ngày. Thành công là muy nhất bạn và bản thân mình mà thôi.', null, 30),
    ('public', '2023-07-25', 'Lo lắng không làm cho những điều tồi tệ ngừng xảy ra mà nó chỉ làm cho những điều tốt lành ngừng lại.', null, 31),
#     ('public', '2023-07-25', 'Đừng chọn mua một quyển sách vì một cái bìa. Và cũng đừng phán xét người khác vì vẻ bề ngoài.', null, 32),
#     ('public', '2023-07-25', 'Trăm lối đi chỉ muốn một lối về. Trăm người cần chỉ muốn một người mong.', null, 32),
    ('public', '2023-07-25', 'một cái thùng rác trên tay bạn sẽ bỏ qua rất nhiều món quà tốt đẹp. Tâm trạng cũng thế, tình cảm cũng vậy.', null, 32),
    ('public', '2023-07-25', 'Đừng bao giờ hối tiếc những điều xảy ra trong quá khứ, vì thời điểm ấy, đó chính xác là những gì bạn muốn.i.', null, 33),
    ('public', '2023-07-25', 'Chỉ khi người giàu ốm, họ mới hiểu sự bất lực của giàu sa', null, 33),
    ('public', '2023-07-25', 'Sức khỏe thật sự là một món của cải to lớn mà không thể đong đếm bằng giá trị của vàng bạc.', null, 34),
    ('public', '2023-07-25', 'Một thân thể không ốm đau, một tinh thần không loạn: đó là hạnh phúc.', null, 35),
    ('public', '2023-07-25', 'Giấc ngủ là sợi dây vàng liên kết sức khỏe và cơ thể bạn..', null, 35),
    ('public', '2023-07-25', 'Sức khỏe là thứ mà ta không nhìn thấy được, là  của mỗi con người; Hãy nâng niu quý t để khi mất rồi mới thấy hối tiếc', null, 35),
    ('public', '2023-07-25', 'Vận động hầu như có thể thay thế cho bất kỳ một thứ thuốc nào. Nhưng bất kỳ một thứ thuốc  thể thay thế cho vận động..', null, 36),
#     ('public', '2023-07-25', 'Vẻ đẹp bên ngoài bắt nguồn từ sức khỏe bên trong', null, 36),
#     ('public', '2023-07-25', 'You only live once, but if you do it right, once is enough', null, 36),
    ('public', '2023-07-25', 'Sự  mất, biết được buông bỏ, học cách viên dung, hóa giải mâu thuẫn. Hiểu được từ bỏ sẽ đạt đến vẻ đẹp của sự trưởng thành.', null, 36),
    ('public', '2023-07-25', 'Đừng bao giờ giao bí mật của bạn cho một ai, bởi vì, tự bạn còn không giữ được thì còn trông mong vào ai kia chứ?”.', null, 37),
    ('public', '2023-07-25', 'Sự khác biệt duy nhất giữa một ngày tốt đẹp và một ngày tồi tệ nằm ở chính thái độ của bạn..', null, 37),
    ('public', '2023-07-25', 'Đừng nên hỏi tại sao bạn sống. Mà nên hỏi ta phảphúc. Đừng cố tu để thoát khổ, mà hãy tu học để làm mình ngày càng hạnh phúc hơn', null, 37),
#     ('public', '2023-07-25', 'Có bốn thứ người yêu mình thực sự, có bạn bè tri kỷ, có sự nghiệp phát triển từng ngày và có một mái nhà ấm áp, tràn ngập yêu thương.', null, 38),
#     ('public', '2023-07-25', 'Hạnh phúc lớn nhất với chính những gì bạn có. Dù vất vả, khó khăn nhưng ta biết trâ và yêu thương thì nhất định hạnh phúc sẽ mỉm cười với ta', null, 38),
    ('public', '2023-07-25', 'Nơi lạnh nhất không phải là Bắc cực mà là nơi không có  hạnh phúc ận lợi nào mà là một người có thái độ sống tốt trước bất kỳ hoàn cảnh nào.', null, 38),
    ('public', '2023-07-25', 'Nơi lạnh nhất không phải là Bắc cực mà là nơi không có tình người.', null, 39),
    ('public', '2023-07-25', 'Cuộc sống của bạn chỉ thật sự ý nghĩa và trọn vẹn khi bạn biết giữ gìn và nuôi dưỡng ước mơ, biết ghi nhận, biết tin vào những lời hứa.', null, 39),
    ('public', '2023-07-25', 'Không vấp ngã trước cuộc sống, điều đó là rất tốt. Nhưng vấp ngã rồi đứng dậy mà đi lên càng tốt hơn.”', null, 39),
    ('public', '2023-07-25', 'Nếu bắt đầu thì có khả năng bạn sẽ nhận lấy thất bại, nhưng nếu không bắt đầu thì bạn đã thất bại rồi', null, 40),
    ('public', '2023-07-25', '“Sự khác biệt giữa những người thành công và những người thất bại không phải là ở sức mạnh, kiến thức hay sự hiểu biết mà chính là ở ý ch', null, 33)
#     ('public', '2023-07-25', 'TDũng cảm là vượt qua nỗi sợ hãi chứ không phải không sợ hãi.', null, 41),
#     ('public', '2023-07-25', 'Hãy làm việc chăm chỉ và lạc quan, và bạn sẽ đạt được mọi thứ mà mình muốn..', null, 41)